# Generated by Django 5.1.3 on 2025-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0002_alter_medicationreminder_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicationreminder",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicationreminder",
            name="user",
        ),
        migrations.AlterField(
            model_name="medicationreminder",
            name="days_of_week",
            field=models.CharField(max_length=50),
        ),
    ]
