# Generated by Django 5.1.6 on 2025-03-19 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('reminder_time', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_documents', models.TextField()),
                ('reminder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reminder_app.reminder')),
            ],
        ),
    ]
