# Generated by Django 5.1.7 on 2025-04-11 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='appointment_type',
            field=models.CharField(choices=[('consulta_general', 'Consulta General'), ('consulta_especialista', 'Consulta con Especialista'), ('analisis_clinico', 'Análisis Clínico'), ('vacunacion', 'Vacunación'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
