# Generated by Django 5.1.7 on 2025-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0002_alter_reminder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='appointment_type',
            field=models.CharField(choices=[('general', 'Consulta General'), ('especialista', 'Consulta con Especialista'), ('analisis', 'Análisis Clínico'), ('vacunacion', 'Vacunación'), ('otros', 'Otros')], default='general', max_length=20),
        ),
    ]
