# Generated by Django 5.1.7 on 2025-04-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalia_app', '0002_remove_documento_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
