# Generated by Django 5.1.6 on 2025-03-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalIA_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PrecioMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitalIA_app.farmacia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitalIA_app.medicamento')),
            ],
        ),
        migrations.DeleteModel(
            name='InventarioFarmacia',
        ),
    ]
