# Generated by Django 5.1.6 on 2025-03-03 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalIA_app', '0002_remove_farmacia_telefono_alter_farmacia_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='StockMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='vitalIA_app.farmacia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='vitalIA_app.medicamento')),
            ],
            options={
                'unique_together': {('farmacia', 'medicamento')},
            },
        ),
        migrations.DeleteModel(
            name='PrecioMedicamento',
        ),
    ]
