# Generated by Django 5.1.6 on 2025-03-03 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalIA_app', '0003_alter_farmacia_nombre_alter_medicamento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockmedicamento',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PrecioMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitalIA_app.farmacia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitalIA_app.medicamento')),
            ],
            options={
                'unique_together': {('farmacia', 'medicamento')},
            },
        ),
    ]
