# Generated by Django 5.1.6 on 2025-03-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitalIA_app', '0004_alter_stockmedicamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockmedicamento',
            unique_together={('farmacia', 'medicamento')},
        ),
        migrations.DeleteModel(
            name='PrecioMedicamento',
        ),
    ]
