# Generated by Django 5.1.6 on 2025-04-21 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_especialidad_medicalresult_doctor_cita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='especialidad',
        ),
        migrations.DeleteModel(
            name='MedicalResult',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
